

require("@nomiclabs/hardhat-waffle")
require("hardhat-gas-reporter")
require("@nomiclabs/hardhat-etherscan")
require("./tasks/block-number")
require("dotenv").config()
require("solidity-coverage")
// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more
/**
 * @type import('hardhat/config').HardhatUserConfig
 */

const COINMARKETCAP_API_KEY = process.env.COINMARKETCAP_API_KEY || "0ac54f3e-fd0a-4f37-9e75-43a98e67ee36"
const GOERLI_RPC_URL =
  process.env.GOERLI_RPC_URL ||
  "https://eth-goerli.g.alchemy.com/v2/UchvT83Y1Kddxk2LNLNp3jkhT_kCu0SM"
const PRIVATE_KEY =
  process.env.PRIVATE_KEY ||
  "d38c99743339c3e8090f35771ec12bcc25cec422df807d4dc1190c608e52a4da"
const ETHERSCAN_API_KEY = process.env.ETHERSCAN_API_KEY || "RXNYPWYW15XXJAWCQP2HWA99RF7RH8TVRX"

module.exports = {
  defaultNetwork: "hardhat",
  networks: {
    hardhat: {},
    goerli: {
      url: GOERLI_RPC_URL,
      accounts: [PRIVATE_KEY],
      chainId: 5,
    },
    localhost: {
      url: " http://127.0.0.1:8545/",
      //Accounts: automatically generated by hardhat. Can check accounts using command "npx hardhat node"
      chainId: 31337,
    },
  },
  solidity: "0.8.8",
  etherscan: {
    apiKey: ETHERSCAN_API_KEY,
  },
  gasReporter: {
    enabled: true,
    currency: "USD",
    outputFile: "gas-report.txt",
    noColors: true,
    coinmarketcap: COINMARKETCAP_API_KEY,
  },
} 